import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, RefreshCw } from 'lucide-react';
import { GlassCard } from './GlassCard';

export function InspirationWidget() {
  const [quote, setQuote] = useState<string>('');
  const [loading, setLoading] = useState<boolean>(true);

  const fetchQuote = async () => {
    setLoading(true);
    try {
      const response = await fetch('/api/inspire');
      if (!response.ok) throw new Error('API Error');
      const data = await response.json();
      setQuote(data.text);
    } catch (error) {
      console.error(error);
      setQuote('Teruslah melangkah, satu kebaikan pada satu waktu.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchQuote();
  }, []);

  return (
    <GlassCard intensity="medium" className="relative overflow-hidden group flex flex-col h-full min-h-[300px] justify-between">
      <div className="absolute top-0 right-0 -mt-10 -mr-10 w-32 h-32 bg-purple-500/20 blur-3xl rounded-full pointer-events-none group-hover:bg-purple-500/30 transition-colors duration-700"></div>
      
      <div className="flex items-center justify-between text-white/50 mb-6">
        <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest">
          <Sparkles className="w-4 h-4 text-cyan-400" />
          <span>AI Insight</span>
        </div>
        <button 
          onClick={fetchQuote} 
          disabled={loading}
          className="p-2 -mr-2 rounded-full hover:bg-white/10 transition-colors disabled:opacity-50"
        >
          <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      <div className="relative flex-1 flex items-center justify-center p-4">
        <AnimatePresence mode="wait">
          {loading ? (
            <motion.div
              key="loader"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex gap-2"
            >
              {[0, 1, 2].map((i) => (
                <motion.div
                  key={i}
                  className="w-2 h-2 bg-cyan-400 rounded-full"
                  animate={{ y: [0, -10, 0] }}
                  transition={{ duration: 0.6, repeat: Infinity, delay: i * 0.15 }}
                />
              ))}
            </motion.div>
          ) : (
            <div className="flex flex-col items-center">
              <motion.p
                key="content"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="text-xl md:text-2xl font-light leading-relaxed text-center text-white/90"
              >
                {quote}
              </motion.p>
              <div className="mt-8 text-[10px] text-cyan-400 font-mono tracking-widest uppercase">Generated by Synapse AI</div>
            </div>
          )}
        </AnimatePresence>
      </div>
    </GlassCard>
  );
}
